# API Parameters Configuration File
# Refer to the official documentation for more details

[BASE_FILTERS]
country = "it"  # Country code for the website (required) [string]
operation = "sale"  # Type of operation (required) [string]
propertyType = "homes"  # Type of property (required) [string]
center = "40.353,18.174"  # Geographic coordinates for search center (WGS84) (latitude, longitude) [string]
distance = 4000  # Distance to center, in meters (ratio) [integer]. Check also https://www.calcmaps.com/map-radius/
locale = "it"  # Search language for summary [string]
locationId = ""  # Idealista location code [string]
maxItems = 50  # Items per page (maximum allowed: 50) [integer]
numPage = ""  # Page number for pagination (1, 2, 3..n) [integer]
maxPrice = 200000  # Maximum price in response [double]
minPrice = 10000  # Minimum price in response [double]
sinceDate = ""  # Property age (W:last week, M: last month, T:last day (for rent except rooms), Y: last 2 days (sale and rooms)) [string]
order = "publicationDate"  # Allowed sorting values by property type [string]
sort = "desc"  # Sort order (asc or desc) [string]
adIds = ""  # Filter by adid (multivalued field) [array]
hasMultimedia = true  # Retrieve properties with pictures or video or virtual tour [boolean]

[HOME_FILTERS]
minSize = 35  # min size (from 60 m2 to 1000m2) [double]
maxSize = 180  # max size (from 60 m2 to 1000m2) [double]
virtualTour = ""  # virtual tour [boolean]
flat = true  # property is a flat [boolean]
penthouse = false  # [boolean]
duplex = true  # [boolean]
studio = ""  # [boolean]
chalet = true  # [boolean]
countryHouse = true  # [boolean]
bedrooms = "1,2,3,4"  # bedroom number (multivalued field: 0,1,2,3,4) [string]
bathrooms = "1,2,3"  # bathroom number (multivalued field: 0,1,2,3) [string]
preservation = ""  # property preservation (good, renew) [string]
newDevelopment = ""  # if true, return only new development properties [boolean]
furnished = ""  # (furnished, furnishedKitchen) [string]
bankOffer = ""  # owner is a bank [boolean]
garage = ""  # has garage [boolean]
terrance = ""  # has terrance [boolean]
exterior = ""  # [boolean]
elevator = ""  # [boolean]
swimmingPool = false  # [boolean]
airConditioning = ""  # [boolean]
storeRoom = ""  # [boolean]
clotheslineSpace = ""  # [boolean]
builtinWardrobes = ""  # [boolean]
subTypology = ""  # chalet subtypology (for propertyType = homes and chalet = true) [string]